checks:
    php: true
filter:
    paths:
        - system/library/*
checks:
    php:
        verify_property_names: true
        verify_argument_usable_as_reference: true
        avoid_entity_manager_injection: false
        duplication: false
        symfony_request_injection: false
        too_many_arguments: false
        uppercase_constants: true
        use_self_instead_of_fqcn: true
